#!/usr/bin/env sh
set -eu

export AGENSENSE_TTS_SAY_ADDR="${AGENSENSE_TTS_SAY_ADDR:-127.0.0.1:18082}"
export AGENSENSE_TTS_SAY_VOICE="${AGENSENSE_TTS_SAY_VOICE:-Tingting}"
export AGENSENSE_TTS_SAY_SAMPLE_RATE="${AGENSENSE_TTS_SAY_SAMPLE_RATE:-16000}"
export AGENSENSE_TTS_SAY_CHANNELS="${AGENSENSE_TTS_SAY_CHANNELS:-1}"
export AGENSENSE_TTS_SAY_CHUNK_BYTES="${AGENSENSE_TTS_SAY_CHUNK_BYTES:-1024}"

exec go run ./cmd/agensense-tts-say
