#!/usr/bin/env sh
set -eu

export AGENSENSE_ADDR="${AGENSENSE_ADDR:-:8080}"
export AGENSENSE_PUBLIC_BASE_URL="${AGENSENSE_PUBLIC_BASE_URL:-http://127.0.0.1:8080}"
export AGENSENSE_DATA_DIR="${AGENSENSE_DATA_DIR:-tmp/agensense}"
export AGENSENSE_LOG_LEVEL="${AGENSENSE_LOG_LEVEL:-info}"
export AGENSENSE_OPENAI_REASONING_EFFORT="${AGENSENSE_OPENAI_REASONING_EFFORT:-none}"
export AGENSENSE_OPENAI_TTS_VOICE="${AGENSENSE_OPENAI_TTS_VOICE:-none}"
export AGENSENSE_OPENAI_TTS_RESPONSE_FORMAT="${AGENSENSE_OPENAI_TTS_RESPONSE_FORMAT:-pcm}"
export AGENSENSE_OPENAI_TTS_SENTENCE_STREAM="${AGENSENSE_OPENAI_TTS_SENTENCE_STREAM:-1}"
export AGENSENSE_OPENAI_TTS_SEGMENT_MAX_RUNES="${AGENSENSE_OPENAI_TTS_SEGMENT_MAX_RUNES:-32}"
export AGENSENSE_OPENAI_TTS_SEGMENT_SILENCE_MS="${AGENSENSE_OPENAI_TTS_SEGMENT_SILENCE_MS:-80}"
export AGENSENSE_REALTIME_TTS_MAX_RUNES="${AGENSENSE_REALTIME_TTS_MAX_RUNES:-28}"
export AGENSENSE_REALTIME_TTS_SOFT_MIN_RUNES="${AGENSENSE_REALTIME_TTS_SOFT_MIN_RUNES:-20}"

exec go run ./cmd/agensense
